services:
  mongodb:
    image: mongo:4
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    restart: always
